Models/Movie.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using MovieStore.Data;
using MovieStore.DB;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

#nullable enable

namespace MovieStore.Models
{
    public class Movie
    {

        public Guid MovieId { get; set; }
        public string Title { get; set; }
        public string? OriginalTitle { get; set; }

        [Column(TypeName = "decimal(18,4)")]
        public decimal Runtime { get; set; }
        public string? Synopsis { get; set; }
        public string? PosterPath { get; set; }
        public DateTime ReleaseDate { get; set; }

        public DateTime? InitRent { get; set; }

        public DateTime? EndRent { get; set; }
        public string? ApiId { get; set; }
        public Guid UserId { get; set; }
        public string OriginalLanguage { get; set; }
        public ICollection<MovieGenre> MovieGenres { get; set; }


        public static Movie MovieJsonToMovie(MovieJson movieJson, ConfigurationJson configJson)
        {
            Movie movie = new Movie();

            if (movieJson.title != null) movie.Title = movieJson.title;
            movie.Runtime = movieJson.runtime;
            movie.ApiId = movieJson.id.ToString();
            if (movieJson.release_date != string.Empty ) movie.ReleaseDate = DateTime.Parse(movieJson.release_date);
            if (movieJson.overview != null) movie.Synopsis = movieJson.overview;
            if (movieJson.poster_path != null && configJson.images.base_url != null) 
                movie.PosterPath = configJson.images.base_url + "w500"+ movieJson.poster_path;
            if (movieJson.original_language != null) movie.OriginalLanguage = movieJson.original_language;
            else movie.OriginalLanguage = "Not Defined";
            if (movieJson.original_title != null) movie.OriginalTitle = movieJson.original_title;

            //foreach (var Genre in movieJson.genres)
            //    movie.MovieGenres.Add(new MovieGenre(movie.MovieId,Guid.Empty)) ;
            return movie;
        }

        
        public static void InsertMovie(Movie movie, DateTime endDate, DateTime startDate, Guid userId)
        {
            using (MovieStoreContext dbContext = new MovieStoreContext())
            {
                movie.MovieId = Guid.NewGuid();
                movie.InitRent = startDate;
                movie.EndRent = endDate;
                movie.UserId = userId;
                dbContext.Add(movie);

                List<Genre> dbGenres = dbContext.Genre.ToList();

                List<MovieJson.Genre> movieGenres = JSONMethods.GetMovieGenres(movie.ApiId);
                foreach (var movieGenre in movieGenres)
                {
                    var x = dbGenres.Find(dbGenre => dbGenre.JsonGenreId == movieGenre.id.ToString());
                    if (x is null)
                    {
                        Genre insertGenre = new Genre();
                        insertGenre.GenreId = Guid.NewGuid();
                        insertGenre.JsonGenreId = movieGenre.id.ToString();
                        insertGenre.Name = movieGenre.name;
                        dbContext.Add(insertGenre);

                        MovieGenre insertedMovieGenre = new MovieGenre();
                        insertedMovieGenre.GenreId = insertGenre.GenreId;
                        insertedMovieGenre.MovieId = movie.MovieId;
                        dbContext.Add(insertedMovieGenre);
                    }
                    else
                    {
                        MovieGenre insertedMovieGenre = new MovieGenre();
                        insertedMovieGenre.GenreId = x.GenreId;
                        insertedMovieGenre.MovieId = movie.MovieId;
                        dbContext.Add(insertedMovieGenre);
                    }

                }
                dbContext.SaveChanges();
            }
        }


        public static List<Movie> GetMovieByUserId(string userId)
        {
            using (var context = new MovieStoreContext())
            {

                return context.Movie.Where(u=>u.UserId == Guid.Parse(userId)).ToList();
            }
        }


    }

    }

Models/Movie/ConfigurationJson.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieStore.Models
{
    public class ConfigurationJson
    {
        public Images images { get; set; }
        public IList<string> change_keys { get; set; }

        
        public class Images
        {
            public string base_url { get; set; }
            public string secure_base_url { get; set; }
            public IList<string> backdrop_sizes { get; set; }
            public IList<string> logo_sizes { get; set; }
            public IList<string> poster_sizes { get; set; }
            public IList<string> profile_sizes { get; set; }
            public IList<string> still_sizes { get; set; }

        }
        


    }
}

Models/Movie/Movie.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using MovieStore.Data;
using MovieStore.DB;
using MovieStore.Models.Genres;
using MovieStore.Models.MovieVideos;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

#nullable enable

namespace MovieStore.Models.Movie
{
    public class Movie
    {

        public Guid MovieId { get; set; }
        public string Title { get; set; }
        public string? OriginalTitle { get; set; }

        [Column(TypeName = "decimal(18,4)")]
        public decimal Runtime { get; set; }
        public string? Synopsis { get; set; }
        public string? PosterPath { get; set; }
        public DateTime ReleaseDate { get; set; }

        public DateTime? InitRent { get; set; }

        public DateTime? EndRent { get; set; }
        public string? ApiId { get; set; }
        public Guid UserId { get; set; }
        public string OriginalLanguage { get; set; }

        [Column(TypeName = "decimal(18,4)")]
        public decimal Popularity { get; set; }
        public ICollection<MovieGenre> MovieGenres { get; set; }


        public static Movie MovieJsonToMovie(MovieJson movieJson, ConfigurationJson configJson)
        {
            Movie movie = new Movie();

            if (movieJson.title != null) movie.Title = movieJson.title;
            movie.Runtime = movieJson.runtime;
            movie.ApiId = movieJson.id.ToString();
            if (movieJson.release_date != string.Empty ) movie.ReleaseDate = DateTime.Parse(movieJson.release_date);
            if (movieJson.overview != null) movie.Synopsis = movieJson.overview;
            if (movieJson.poster_path != null && configJson.images.base_url != null) 
                movie.PosterPath = configJson.images.base_url + "w342"+ movieJson.poster_path;
            if (movieJson.original_language != null) movie.OriginalLanguage = movieJson.original_language;
            else movie.OriginalLanguage = "Not Defined";
            if (movieJson.original_title != null) movie.OriginalTitle = movieJson.original_title;
            movie.Popularity = (decimal)movieJson.popularity;

            return movie;
        }

        
        public static void InsertMovie(Movie movie, DateTime endDate, DateTime startDate, Guid userId)
        {
            using (MovieStoreContext dbContext = new MovieStoreContext())
            {
                movie.MovieId = Guid.NewGuid();
                movie.InitRent = startDate;
                movie.EndRent = endDate;
                movie.UserId = userId;
                dbContext.Add(movie);

                List<Genre> dbGenres = dbContext.Genre.ToList();

                List<MovieJson.Genre> movieGenres = JSONMethods.GetMovieGenres(movie.ApiId);
                foreach (var movieGenre in movieGenres)
                {
                    Genre? x = dbGenres.Find(dbGenre => dbGenre.JsonGenreId == movieGenre.id.ToString());
                    if (x is null)
                    {
                        Genre insertGenre = new Genre();
                        insertGenre.GenreId = Guid.NewGuid();
                        insertGenre.JsonGenreId = movieGenre.id.ToString();
                        insertGenre.Name = movieGenre.name;
                        dbContext.Add(insertGenre);

                        MovieGenre insertedMovieGenre = new MovieGenre();
                        insertedMovieGenre.GenreId = insertGenre.GenreId;
                        insertedMovieGenre.MovieId = movie.MovieId;
                        dbContext.Add(insertedMovieGenre);
                    }
                    else
                    {
                        MovieGenre insertedMovieGenre = new MovieGenre();
                        insertedMovieGenre.GenreId = x.GenreId;
                        insertedMovieGenre.MovieId = movie.MovieId;
                        dbContext.Add(insertedMovieGenre);
                    }

                }
                dbContext.SaveChanges();
            }
        }


        public static List<Movie> GetMovieByUserId(string userId)
        {
            using (var context = new MovieStoreContext())
            {

                return context.Movie.Where(u => u.UserId == Guid.Parse(userId)).ToList();
            }
        }

        public static Movie? GetMovieByJsonMovieId(string movieId)
        {
            using (var context = new MovieStoreContext())
            {

                return context.Movie.Where(u => u.ApiId == movieId).FirstOrDefault();
            }
        }

    }

    }

Models/Movie/MovieJson.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieStore.Models
{
    public class MovieJson
    {
         public bool adult { get; set; }
         public string backdrop_path { get; set; }
         public object belongs_to_collection { get; set; }
         public int budget { get; set; }
         public List<Genre> genres { get; set; }
         public string homepage { get; set; }
         public int id { get; set; }
         public string imdb_id { get; set; }
         public string original_language { get; set; }
         public string original_title { get; set; }
         public string overview { get; set; }
         public double popularity { get; set; }
         public string poster_path { get; set; }
         public List<ProductionCompany> production_companies { get; set; }
         public List<ProductionCountry> production_countries { get; set; }
         public string release_date { get; set; }
         public int revenue { get; set; }
         public int runtime { get; set; }
         public List<SpokenLanguage> spoken_languages { get; set; }
         public string status { get; set; }
         public string tagline { get; set; }
         public string title { get; set; }
         public bool video { get; set; }
         public double vote_average { get; set; }
         public int vote_count { get; set; }

        public class Genre
        {
            public int id { get; set; }
            public string name { get; set; }
        }

        public class ProductionCompany
        {
            public int id { get; set; }
            public string logo_path { get; set; }
            public string name { get; set; }
            public string origin_country { get; set; }
        }

        public class ProductionCountry
        {
            public string iso_3166_1 { get; set; }
            public string name { get; set; }
        }

        public class SpokenLanguage
        {
            public string english_name { get; set; }
            public string iso_639_1 { get; set; }
            public string name { get; set; }
        }

    }
}

Models/Movie/MovieLanguage.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieStore.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieStore.Models
{
    public class MovieLanguage
    {
        public Guid MovieLanguageId { get; set; }
        public string Name { get; set; }
        public string NameJson { get; set; }


        public static List<MovieLanguage> GetMovieLanguages()
        {
            using (var context = new MovieStoreContext())
            {

                return context.MovieLanguage.ToList();
            }
        }

    }
}

Controllers/ActorController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieStore.DB;
using MovieStore.Models.Actor;
using MovieStore.Models.Cast;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieStore.Controllers
{
    public class ActorController : Controller
    {

        private readonly UserManager<IdentityUser> _userManager;

        public ActorController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }



        
        public IActionResult Index()
        {

            string actorId = HttpContext.Request.RouteValues.Values.Last().ToString();
            PersonView actor = new PersonView(actorId);
            return View(actor);
        }
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using MovieStore.Data;
using MovieStore.DB;
using MovieStore.Models;
using MovieStore.Models.Genres;
using MovieStore.Models.Movie;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace MovieStore.Controllers
{
    public class MovieController : Controller
    {

        private readonly UserManager<IdentityUser> _userManager;

        public MovieController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }



        [HttpGet]
        public IActionResult Index()
        {
            ViewData["Language"] = new SelectList(MovieLanguage.GetMovieLanguages(), "NameJson", "Name");
            ViewData["Genres"] = new SelectList(Genre.GetGenres(), "GenreId", "Name");
            Genre m = new Genre();
            return View(m);
        }




        [HttpGet]
        public IActionResult MovieSearch(string searchString, string language, int page, int current_result, int page_number_language)
        {
            if (searchString != null)
            {
                string args = JSONMethods.BuildSearchString(searchString, null, page);
                string jsonStringMovieSearch = JSONMethods.JsonApiRequest("https://api.themoviedb.org/3/search/movie?api_key=5933922b6587d2d506362381025ef410"
                   + args);

                MoviesSearchListJson list = JsonConvert.DeserializeObject<MoviesSearchListJson>(jsonStringMovieSearch);
                list.searchString = searchString;
                list.PaginatedByLanguage(language, page_number_language, current_result);

                return View(list);
            }
            else
                return View();
        }

      

        public IActionResult MovieReserve()
        {
            string movieId = HttpContext.Request.QueryString.Value.Substring(HttpContext.Request.QueryString.Value.LastIndexOf('=') + 1);

            ViewData["Post"] = false;
            return View(JSONMethods.GetMovie(movieId));
        }


        [HttpPost]
        public IActionResult MovieReserve(DateTime startDate, DateTime endDate, string movieId)
        {
            Movie movie = JSONMethods.GetMovie(movieId);
            int status = DataManipulation.CheckMovieReservationStatus(startDate, endDate, movie);
            ViewData["Post"] = true;
            ViewData["Status"] = status;

            if (status == 1 )//movie can be reserved
            {
                string userId = _userManager.GetUserId(HttpContext.User);
                Movie.InsertMovie(movie, endDate, startDate, Guid.Parse(userId));
                return View(movie); 
            }
            else
            { 
                return View(movie);
            }
        }


        public IActionResult MoviePrint()
        {
            string movieId = HttpContext.Request.QueryString.Value.Substring(HttpContext.Request.QueryString.Value.LastIndexOf('=') + 1);
            if (string.IsNullOrEmpty(movieId))
                movieId = HttpContext.Request.RouteValues["id"].ToString();
            Movie movie = JSONMethods.GetMovie(movieId);
            MovieView view = new MovieView(movie);

            return View(view);
        }



    }
}

Controllers/MyMoviesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieStore.Models.Movie;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieStore.Controllers
{
    public class MyMoviesController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;

        public MyMoviesController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            string userId = _userManager.GetUserId(HttpContext.User);
            List<Movie> movies = Movie.GetMovieByUserId(userId);
            return View(movies);
        }
    }
}

Views/Movie/Index.cshtml
<form asp-controller="Movie" asp-action="MovieSearch" method="get">
    <label for="MovieTitle">Search Movie</label>
    <input type="text" id="searchString" placeholder="Search" name="searchString" />
    <input type="submit" />

    @Html.DropDownList("language", (IEnumerable
   <SelectListItem>)ViewData["Language"], "--Select Language--")


</form>




<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
<link href="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />
<script src="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/js/bootstrap-multiselect.js" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        $('.listbox').multiselect({
            includeSelectAllOption: true
        });
    });
</script>

Views/Movie/MoviePrint.cshtml
@using MovieStore.Models.Movie
@model MovieView




<div class="text-center" style="font-size : 100px">
    <h1 class="display-4">@(Model.Movie.Title + "  (" + Model.Movie.ReleaseDate.Year + ')' )</h1>
</div>
<body>
    <div style="width: 100%;">
        <div style="width: 50%; float: left;font-size : 20px">
            <img src="@Model.Movie.PosterPath" class="detailImage" />
            <p><b>Directed by: @Model.Director</b></p>
            <p style="font-size: 17px"><b>Screenplay by: @Model.Screenplay</b></p>
        </div>
        <div style="margin-left: 50%; height: 200px; ">
            @Model.Movie.Synopsis
        </div>
        <div style="margin-left: 50%; height: 400px; ">
            @Html.ActionLink("Reserve", "MovieReserve", new { @Model.Movie.ApiId }, null)
        </div>
    </div>
    <div style="height: 500px">
        <h1>
            Trailer
        </h1>
        @if (Model.YoutubeVideo.YoutubeLink != null)
        {
            <iframe type="text/html" width="640" height="385" src="@Model.YoutubeVideo.YoutubeLink" frameborder="0">
            </iframe>
        }
        else
        {
            <b>No Trailer currently exists.</b>
        }
    </div>
</body>

<table class="table">
    <thead>
        Cast Info
    </thead>
    <tbody>
        @foreach (var cast in Model.Cast.cast)
        {
            <tr>
                <td><img src= @cast.profile_path class="detailImage" /></td>
                <td><b>@Html.ActionLink(cast.name, "Index", "Actor", new { cast.id }, null)</b></td>
                <td><b>as @cast.character </b></td>
            </tr>
        }
    </tbody>
</table>

Views/Movie/MovieReserve.cshtml
@using MovieStore.Models.Movie
@model Movie

@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers

@if ((bool)ViewData["Post"] == false)
{


    <!DOCTYPE html>
    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Index</title>
    </head>
    <body>
        <script type="text/javascript" src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js'></script>
        <script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js'></script>
        <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css'
              media="screen" />

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" type="text/css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js" type="text/javascript"></script>

        <div style="width:100%">
            <form asp-controller="Movie" asp-action="MovieReserve" method="post">
                Reserve From:
                <input type="text" id="startDate" name="startDate" readonly="readonly" />
                <input type="submit" value="Submit" style="margin-left:10%" />
                To:
                <input type="text" id="endDate" name="endDate" readonly="readonly" />
                <input type="hidden" name="movieId" value="@Model.ApiId" />

                <script type="text/javascript">
                    $(function () {
                        $('#startDate').datepicker({
                            changeMonth: true,
                            changeYear: true,
                            format: "dd/mm/yyyy",
                            language: "tr"
                        });
                    });
                </script>
                @if (ViewBag.Message != null)
                {
                    <script type="text/javascript">
            $(function () {
                alert("@ViewBag.Message");
            });
                    </script>
                }


                <script type="text/javascript">
                    $(function () {
                        $('#endDate').datepicker({
                            changeMonth: true,
                            changeYear: true,
                            format: "dd/mm/yyyy",
                            language: "tr"
                        });
                    });
                </script>
                @if (ViewBag.Message != null)
                {
                    <script type="text/javascript">
            $(function () {
                alert("@ViewBag.Message");
            });
                    </script>
                }
            </form>

        </div>


    </body>
</html>
}
else
{
int status = (int)ViewData["Status"];
@switch (status)
{



    case (1):
        <p><em>Your movie @Model.Title has been successfully reserved.</em></p>

        <body>
            <div style="width: 100%;">
                <div style=" width: 50%; height: 100px;">
                    @Html.ActionLink("Search more movies.", "Index")
                </div>
            </div>
        </body>
        break;



    case (2):



        <html>
        <head>
            <meta name="viewport" content="width=device-width" />
            <title>Index</title>
        </head>
        <body>
            <script type="text/javascript" src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js'></script>
            <script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js'></script>
            <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css'
                  media="screen" />

            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" type="text/css" />
            <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js" type="text/javascript"></script>

            <div style="width:100%">
                <form asp-controller="Movie" asp-action="MovieReserve" method="post">
                    Reserve From:
                    <input type="text" id="startDate" name="startDate" readonly="readonly" />
                    <input type="submit" value="Submit" style="margin-left:10%" />
                    To:
                    <input type="text" id="endDate" name="endDate" readonly="readonly" />
                    <input type="hidden" name="movieId" value="@Model.ApiId" />

                    <script type="text/javascript">
                        $(function () {
                            $('#startDate').datepicker({
                                changeMonth: true,
                                changeYear: true,
                                format: "dd/mm/yyyy",
                                language: "tr"
                            });
                        });
                    </script>
                    @if (ViewBag.Message != null)
                    {
                        <script type="text/javascript">
            $(function () {
                alert("@ViewBag.Message");
            });
                        </script>
                    }


                    <script type="text/javascript">
                        $(function () {
                            $('#endDate').datepicker({
                                changeMonth: true,
                                changeYear: true,
                                format: "dd/mm/yyyy",
                                language: "tr"
                            });
                        });
                    </script>
                    @if (ViewBag.Message != null)
                    {
                        <script type="text/javascript">
            $(function () {
                alert("@ViewBag.Message");
            });
                        </script>
                    }
                </form>


            </div>
            <p style="color:red;font-size:150%;"><em>The interval for reservation is not valid.</em></p>


        </body>
    </html>


    break;


case (3):
    <p><em>You already have this movie reserved.</em></p>

    <body>
        <div style="width: 100%;">
            <div style=" width: 50%; height: 100px;">
                @Html.ActionLink("Search more movies.", "Index")
            </div>
        </div>
        <div style="width: 100%;">
            <div style=" width: 50%; height: 200px;">
                @Html.ActionLink("Check your reservations", "Index", "MyMovies")
            </div>
        </div>
    </body>
    break;

case (4):

    <p><em>Unfortunately, this movie is not available at the moment.</em></p>

    <body>
        <div style="width: 100%;">
            <div style=" width: 50%; height: 100px;">
                @Html.ActionLink("Search more movies.", "Index")
            </div>
        </div>
    </body>

    break;

}


}

Views/Movie/MovieSearch.cshtml
@model MoviesSearchListJson


<h1>Search Results</h1>


@if (Model != null && Model.results.Count > 0)
{

    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Synopsis</th>
                <th>More Info</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var Result in Model.results)
            {
                @if (Result.release_date is null)
                    Result.release_date = "T.B.A.";
                <tr>
                    @if (Result.original_language != "en" && !Result.original_title.Contains(Result.title))
                    {
                        <td><b>@(Result.title + " (" + Result.release_date.Split('-')[0] + ") ") </b><p><i> @Result.original_title</i></p></td>
                    }
                    else
                    {
                        <td><b>@(Result.title + " (" + Result.release_date.Split('-')[0] + ") " )</b></td>
}

                    <td>@Result.overview</td>
                    <td>@Html.ActionLink("Info", "MoviePrint", new { Result.id }, null)</td>
                </tr>
            }
        </tbody>
    </table>


    var PreviousDisabled = "";
    if (Model.page == 1) PreviousDisabled = "disabled";
    var NextDisabled = "";
    if (Model.page == Model.total_pages || Model.results.Count<20) NextDisabled = "disabled";


    <div style="margin-left: 40%; font-size : 120px" >
        <a asp-action="MovieSearch"
           asp-route-page="@(Model.page - 1)"
           asp-route-language="@(Model.language)"
           asp-route-searchString="@(Model.searchString)"
           asp-route-current_result="@Model.current_result"
           asp-route-page_number_language="@Model.page_number_language"
           class="btn btn-default @PreviousDisabled" style=" font-size : 30px" >
            Previous

        </a>
    

    
        <a asp-action="MovieSearch"
           asp-route-page="@(Model.page + 1)"
           asp-route-language="@(Model.language)"
           asp-route-searchString="@(Model.searchString)"
           asp-route-current_result="@(Model.current_result) "
           asp-route-page_number_language="@Model.page_number_language"
           class="btn btn-default @NextDisabled" style=" font-size : 30px" >
            Next
        </a>
    </div>
    
    <div style="margin-left: 50%;"> <b>Page @Model.page</b> </div>
    
    }
    else
    {
    <p><em>No results found.</em></p>

    }